# Generated by Django 3.1.3 on 2021-01-04 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='phon_no',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
