# Generated by Django 3.1.3 on 2021-01-04 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0002_users_phon_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='phon_no',
        ),
        migrations.AddField(
            model_name='users',
            name='phone_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
