# Generated by Django 3.1.3 on 2020-11-19 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userUid', models.AutoField(db_column='userUid', primary_key=True, serialize=False)),
                ('firstName', models.CharField(db_column='firstName', max_length=255)),
                ('lastName', models.CharField(db_column='lastName', max_length=255)),
                ('password', models.CharField(db_column='password', max_length=2000)),
                ('token', models.CharField(db_column='token', max_length=2000)),
                ('email', models.CharField(db_column='email', max_length=255, unique=True)),
                ('mobile', models.CharField(db_column='mobile', max_length=255)),
                ('createdDate', models.DateTimeField(auto_now_add=True, db_column='createdDate')),
                ('modifiedDate', models.DateTimeField(auto_now=True, db_column='modifiedDate')),
            ],
            options={
                'db_table': 'Users',
            },
        ),
    ]
