# Generated by Django 3.1.3 on 2020-12-03 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uimanagement', '0002_auto_20201202_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarms',
            name='alarmName',
            field=models.CharField(db_column='alarmName', max_length=255, unique=True),
        ),
    ]
