# Generated by Django 3.1.3 on 2020-11-19 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CameraFeeds',
            fields=[
                ('feedUid', models.AutoField(db_column='feedUid', primary_key=True, serialize=False)),
                ('feedName', models.CharField(db_column='feedName', max_length=255, unique=True)),
                ('camType', models.CharField(db_column='camType', max_length=255)),
                ('feedURL', models.CharField(db_column='feedURL', max_length=2000, unique=True)),
                ('CamFeedObjects', models.TextField(db_column='objects')),
                ('createdDate', models.DateTimeField(auto_now_add=True, db_column='createdDate')),
                ('modifiedDate', models.DateTimeField(auto_now=True, db_column='modifiedDate')),
            ],
            options={
                'db_table': 'CameraFeeds',
            },
        ),
        migrations.CreateModel(
            name='CameraSettings',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('camType', models.CharField(db_column='camType', max_length=255, unique=True)),
                ('alarmType', models.CharField(db_column='alarmType', max_length=255, unique=True)),
                ('rectColours', models.TextField(db_column='rectColours')),
                ('createdDate', models.DateTimeField(auto_now_add=True, db_column='createdDate')),
                ('modifiedDate', models.DateTimeField(auto_now=True, db_column='modifiedDate')),
            ],
            options={
                'db_table': 'CameraSettings',
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('eventUid', models.AutoField(db_column='eventUid', primary_key=True, serialize=False)),
                ('camFeedId', models.IntegerField(db_column='camFeedId')),
                ('eventTime', models.DateTimeField(db_column='eventTime')),
                ('objsDetected', models.TextField(db_column='objsDetected')),
                ('videoPath', models.CharField(db_column='videoPath', max_length=2000, unique=True)),
                ('createdDate', models.DateTimeField(auto_now_add=True, db_column='createdDate')),
                ('modifiedDate', models.DateTimeField(auto_now=True, db_column='modifiedDate')),
            ],
            options={
                'db_table': 'Events',
            },
        ),
    ]
