# Generated by Django 3.1.3 on 2020-12-02 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uimanagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alarms',
            fields=[
                ('alarmUid', models.AutoField(db_column='alarmUid', primary_key=True, serialize=False)),
                ('alarmName', models.IntegerField(db_column='alarmName', unique=True)),
                ('originalFileName', models.TextField(db_column='originalFileName')),
                ('datafile', models.FileField(upload_to='')),
                ('createdDate', models.DateTimeField(auto_now_add=True, db_column='createdDate')),
                ('modifiedDate', models.DateTimeField(auto_now=True, db_column='modifiedDate')),
            ],
            options={
                'db_table': 'Alarms',
            },
        ),
        migrations.CreateModel(
            name='ProcessState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(db_column='status', default=0)),
            ],
            options={
                'db_table': 'ProcessState',
            },
        ),
        migrations.RemoveField(
            model_name='camerasettings',
            name='alarmType',
        ),
        migrations.AddField(
            model_name='camerasettings',
            name='alarm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='uimanagement.alarms'),
        ),
    ]
